### ISSUE TITLE
FIX does not run on latest Jetbrains IDEA Ultimate

### ISSUE THREAD

**Issue by allanlaal** [sloppylopez/moneypenny-idea-plugin#35]
tried changing the max ver in META-INF, but the plugin wont load properly still

**Comment by sloppylopez** [comment]
yo, i am coming back to this, working on it, just give me few days

**Comment by sloppylopez** [comment]
There are also some major improvements coded, i am just testing them for the time being, I abandon this project because I was handling 4 office projects and that was too much, but now I am down to 1 again, so I am coming back to this backlog

**Comment by sloppylopez** [comment]
I got it, I am waiting for jetbrains approval, it shall be done in 1 or 2 days

**Comment by sloppylopez** [comment]
https://plugins.jetbrains.com/plugin/22252-moneypenny-ai/edit/versions/stable/640543
